const BlackCard = require ('../class/BlackCard.js');
const PROPERTIES = require('../properties.js');
module.exports = [
    new BlackCard('Je pense que {x} propose des vraies solutions.', false, 'fr'),
    new BlackCard('Tu préfères {x} ou {x}.', false, 'fr'),
    new BlackCard('Martine {x}.', false, 'fr'),
    new BlackCard('Je me suis fait baisé par {x}.', true, 'fr'),
	new BlackCard('Les Etats-Unis ont débuté le parachutage de {x} aux enfants afhans.', false, 'fr'),
	new BlackCard('La guerre, c\'est bien pour quoi ? {x}', false, 'fr'),
	new BlackCard('Qu\'est-ce qui m\'empêche de dormir ? {x}', false, 'fr'),
	new BlackCard('C\'est quoi cette odeur ? {x}', false, 'fr'),
	new BlackCard('Qui a volé les cookies ? {x}', false, 'fr'),
	new BlackCard('Des études prouvent que les rats de laboratoires se déplacent cinquante fois plus vite dans les labyrinthes après avoir été exposés à {x}.', false, 'fr'),
	new BlackCard('Quand j\'irai en prison, je cacherai {x} dans mes fesses pour faire de la contrebande.', false, 'fr'),
	new BlackCard('Si j\'étais Président de la République, je créerais le ministère de {x}.', false, 'fr'),
	new BlackCard('Qu\'est-ce qui se bonifie avec le temps ? {x}', false, 'fr'),
	new BlackCard('Je bois pour oublier {x}.', false, 'fr'),
	new BlackCard('Qu\'ai-je rapporté du Mexique ? {x}', false, 'fr'),
	new BlackCard('La sortie scolaire a été totalement gâchée par {x}.', false, 'fr'),
	new BlackCard('Qu\'est ce que vous n\'aimeriez pas trouver dans de la nourriture chinoise ? {x}', false, 'fr'),
	new BlackCard('Dans son nouveau film Disney, Hannah Montana affronte {x} pour la toute première fois.', false, 'fr'),
	new BlackCard('Pendant le sexe, j\'aime penser à {x}.', false, 'fr'),
	new BlackCard('A cause de quoi mon slip est-il trempé ? {x}', false, 'fr'),
	new BlackCard('Que me cachent mes parents ? {x}', false, 'fr'),
	new BlackCard('Les blancs aiment bien {x}.', false, 'fr'),
	new BlackCard('A cause de quoi les terroristes nous détestent-ils autant ? {x}', false, 'fr'),
	new BlackCard('Comme j\'aimerais ne pas avoir perdu la notice pour {x}.', false, 'fr'),
	new BlackCard('Désolé les gens, je viens juste de {x}.', false, 'fr'),
	new BlackCard('C\'est quoi ce bruit ? {x}', false, 'fr'),
	new BlackCard('Qu\'est ce qu\'on peut trouver par milliers au paradis ? {x}', false, 'fr'),
	new BlackCard('Le meilleur ami des filles, c'est {x}.', false, 'fr'),
	new BlackCard('Quel est le plaisir coupable de Batman ? {x}', false, 'fr'),
	new BlackCard('Les psychanalystes s\'alarment devant l\'émergence de la phobie de {x} chez la plupart de leurs patients.', false, 'fr'),
	new BlackCard('Quand j\'étais sous acide, {x} se changeait en {y}.', false, 'fr'),
	new BlackCard('Quand j\'étais petit, j\'adorais {x}.', false, 'fr'),
	new BlackCard('Qu\'est ce qui vous fera réussir à coucher à tous les coups ? {x}', false, 'fr'),
	new BlackCard('Et l\'Oscar du meilleur {x} est attribué à {y}.', false, 'fr'),
	new BlackCard('Quel est le prochain duo super-héros/acolyte ? {x}', false, 'fr'),
	new BlackCard('{x} : Bon jusqu\'à la dernière goutte.', false, 'fr'),
	new BlackCard('Désormais, le Père Noël n\'apportera plus du charbon aux vilains enfants mais {x}.', false, 'fr'),
	new BlackCard('Quel est mon super-pouvoir secret ? {x}', false, 'fr'),
	new BlackCard('Pour draguer, il ne faut surtout pas parler de son penchant pour {x}.', false, 'fr'),
	new BlackCard('Que préfère Nicolas Sarkozy ? {x}', false, 'fr'),
	new BlackCard('Qui est le plus aigri ? {x}', false, 'fr'),
	new BlackCard('{x} ? Il y a une application pour ça.', false, 'fr'),
	new BlackCard('Pour mon prochain tour de magie, je vais faire sortir {x} de {y}.', false, 'fr'),
	new BlackCard('Durant sa période marron (souvent négligée), Picasso peignait beaucoup de tableaux représentant {x}.', false, 'fr'),
	new BlackCard('La médecine reconnaût enfin les pouvoirs thérapeutiques de {x}.', false, 'fr'),
	new BlackCard('{x} : Testé par les enfants, approuvé par les mamans.', false, 'fr'),
	new BlackCard('Qu\'est-ce qui peut aider à maintenir une relation de couple ? {x}', false, 'fr'),
	new BlackCard('La vie était dure pour les hommes des cavernes avant {x}.', false, 'fr'),
	new BlackCard('Ce soir sur M6, Bernard de la Villiardière vous propose une enquête exclusive sur {x}.', false, 'fr'),
	new BlackCard('Que sentent les personnes âgées ? {x}', false, 'fr'),
	new BlackCard('Qu\'est ce qui aide Barack Obama à se changer les idées ? {x}', false, 'fr'),
	new BlackCard('Il mange quoi Vin Diesel au petit déjeuner ?', false, 'fr'),
	new BlackCard('Qu\'est-ce que mamie trouve d\'abord perturbant, puis étrangement plaisant ? {x}', false, 'fr'),
	new BlackCard('{x} ? C\'est un piège.', false, 'fr'),
	new BlackCard('Quel est le prochain jouet du Happy Meal ? {x}', false, 'fr'),
	new BlackCard('C\'est vrai, j\'ai tué {x}. Comment ? {y}', false, 'fr'),
	new BlackCard('Si j\'étais riche, je ferais ériger une statue de 15 mètres de haut pour commémorer {x}.', false, 'fr'),
	new BlackCard('Mais avant de vous tuer, Mr Bond, je dois vous montrer.', false, 'fr'),
	new BlackCard('Ce soir sur Canal+ découvrez {x}, la tragique histoire de {y}.', false, 'fr'),
	new BlackCard('Qu\'est-ce qui me donne des gaz inctrôlables ? {x}', false, 'fr'),
	new BlackCard('Qu\'est-ce qui est le plus hardcore ? {x}', false, 'fr'),
	new BlackCard('Qu\'est ce qui est le plus gay ? {x}', false, 'fr'),
	new BlackCard('Alors que les USA et l\'URSS s\'affrontaient dans la course à l\'espace, le Mexique dépensait des millions de pesos dans la recherche sur {x}.', false, 'fr'),
	new BlackCard('Alors que Pharaon restait impassible, Moïse provoqua la onzième plaie : {x}.', false, 'fr'),
	new BlackCard('Je ne sais pas avec quelles armes se fera la Troisième Guerre Mondiale, mais la Quatrième se fera à coups de {x}.', false, 'fr'),
	new BlackCard('Selon une rumeur, le plat préféré de Vladimir Poutine est {x} fourré avec {y}.', false, 'fr'),
	new BlackCard('La dernière chose à laquelle pensa Michaël Jackson avant de mourir fût {x}.', false, 'fr'),
	new BlackCard('Des ethnographes ont récemment découvert une tribu aborigène vouant un culte à {x}.', false, 'fr'),
	new BlackCard('Se retrouver sous respirateur à cause de {x}.', false, 'fr'),
]
