const WhiteCard = require ('../class/WhiteCard.js');

module.exports = [
    new WhiteCard('Hitler', false, 'all'),
    new WhiteCard('Les juifs', false, 'fr'),
    new WhiteCard('Ta mère', false, 'fr'),
    new WhiteCard('Le médecin légiste', false, 'fr'),
    new WhiteCard('Jean-Marie Le Pen', false, 'fr'),
    new WhiteCard('Kastuni', true, 'fr'),
    new WhiteCard('Jean-Pierre Mader', false, 'fr'),
    new WhiteCard('Un doigt dans le cul', true, 'fr'),
    new WhiteCard('Un prince Albert', true, 'fr'),
    new WhiteCard('La sainte Bible', false, 'all'),
    new WhiteCard('La Macarena', false, 'all'),
    new WhiteCard('Se chier dessus', false, 'all'),
    new WhiteCard('Un anus maquillé', false, 'all'),
    new WhiteCard('Les juifs avec une coupe afro', false, 'all'),
    new WhiteCard('Les P\'tits Filous Tubes', false, 'all'),
    new WhiteCard('Une branlette tristement exécutée', false, 'all'),
    new WhiteCard('Des biscuits apéro', false, 'all'),
    new WhiteCard('Mickaël Jackson', false, 'all'),
    new WhiteCard('Batman', false, 'all'),
    new WhiteCard('Les vikings', false, 'all'),
    new WhiteCard('L\'abstinence', false, 'all'),
    new WhiteCard('Le bibendum Michelin', false, 'all'),
    new WhiteCard('Superbus', false, 'all'),
    new WhiteCard('Son Altesse royale, la reine Elizabeth II', false, 'all'),
    new WhiteCard('L\'auto-cannibalisme', false, 'all'),
    new WhiteCard('La série des "Fais-moi peur !"', false, 'all'),
    new WhiteCard('Le ping-pong de caca cul à cul', false, 'all'),
    new WhiteCard('Pour toujours', false, 'all'),
    new WhiteCard('La fête du slip', false, 'all'),
    new WhiteCard('Mes parties génitales', false, 'all'),
    new WhiteCard('L\'inceste', false, 'all'),
    new WhiteCard('L\'Amérique', false, 'all'),
    new WhiteCard('Les chansons de Pascal Obispo', false, 'all'),
    new WhiteCard('Un twist de M. Night Shyamalan', false, 'all'),
    new WhiteCard('Mourir de la dysentrie', false, 'all'),
    new WhiteCard('Les équipes chinoises de gymnastiques', false, 'all'),
    new WhiteCard('Du sexe surprise', false, 'all'),
    new WhiteCard('Batifoler', false, 'all'),
    new WhiteCard('Une tortue vicieuse qui te mord la bite', false, 'all'),
    new WhiteCard('Le lancer de nain sur une cible en velcro', false, 'all'),
    new WhiteCard('2 girls 1 cup', false, 'all'),
    new WhiteCard('La tension sexuelle', false, 'all'),
    new WhiteCard('Une fête d\'anniversaire ratée', false, 'all'),
    new WhiteCard('Du Axe Body Spray', false, 'all'),
    new WhiteCard('Des bébés chiens', false, 'all'),
    new WhiteCard('Les gens qui sentent leurs chaussettes', false, 'all'),
    new WhiteCard('La destruction mutuelle assurée', false, 'all'),
    new WhiteCard('Le Ku Klux Klan', false, 'all'),
    new WhiteCard('Boire tout seul', false, 'all'),
    new WhiteCard('Des abdominaux spectaculaires', false, 'all'),
    new WhiteCard('Faire le bon choix', false, 'all'),
    new WhiteCard('Du sperme de baleine', false, 'all'),
    new WhiteCard('Les inondations', false, 'all'),
    new WhiteCard('Center Park', false, 'all'),
    new WhiteCard('Les Oompas Loompas', false, 'all'),
    new WhiteCard('La capacité d\'écoute', false, 'all'),
    new WhiteCard('Se mettre tellement en colère que ça en donne une érection', false, 'all'),
    new WhiteCard('Les juifsLes cols portés relevés', false, 'all'),
    new WhiteCard('World of Warcraft', false, 'all'),
    new WhiteCard('Faire la moue', false, 'all'),
    new WhiteCard('Gargamel', false, 'all'),
    new WhiteCard('Les Twinkies', false, 'all'),
    new WhiteCard('Le Stade de France', false, 'all'),
    new WhiteCard('Être un sale con envers les enfants', false, 'all'),
    new WhiteCard('Des salopes', false, 'all'),
    new WhiteCard('Les enfants tenus en laisse', false, 'all'),
    new WhiteCard('Laisser un message maladroit sur un répondeur', false, 'all'),
    new WhiteCard('Beaucoup de bruit pour rien', false, 'all'),
    new WhiteCard('Les noirs', false, 'all'),
    new WhiteCard('La lactation', false, 'all'),
    new WhiteCard('Natalie Portman', false, 'all'),
    new WhiteCard('Britneys Spears à 55 ans', false, 'all'),
    new WhiteCard('Les Jazz Hands', false, 'all'),
    new WhiteCard('Une fanfic érotique sur l\'univers d\'Harry Potter', false, 'all'),
    new WhiteCard('Les existentialistes', false, 'all'),
    new WhiteCard('La science', false, 'all'),
    new WhiteCard('Une mycose', false, 'all'),
    new WhiteCard('Chier dans la soupe', false, 'all'),
    new WhiteCard('La puberté', false, 'all'),
    new WhiteCard('Le Pape', false, 'all'),
    new WhiteCard('Abuser des cabines de bronzage', false, 'all'),
    new WhiteCard('Les tétraplégiques', false, 'all'),
    new WhiteCard('Un cinquantenaire qui pratique le roller', false, 'all'),
    new WhiteCard('Se retirer', false, 'all'),
    new WhiteCard('Brouter', false, 'all'),
    new WhiteCard('Péter et s\'en aller', false, 'all'),
    new WhiteCard('Parkinson', false, 'all'),
    new WhiteCard('Auschwitz', false, 'all'),
    new WhiteCard('Des chèvres qui mangent des sacs poubelles', false, 'all'),
    new WhiteCard('Boire un verre de beurre fondu', false, 'all'),
    new WhiteCard('La coulle manquante de Lance Armstrong', false, 'all'),
    new WhiteCard('Le faire dans les fesses', false, 'all'),
    new WhiteCard('La séduction', false, 'all'),
    new WhiteCard('Les Jonas Brothers', false, 'all'),
    new WhiteCard('La sexualité des pandas', false, 'all'),
    new WhiteCard('Un chameau en dessin animé qui apprécie une délicieuse et rafraichissante taffe de cigarette', false, 'all'),
    new WhiteCard('Respirer de la colle', false, 'all'),
    new WhiteCard('Les sites de rencontres échangistes', false, 'all'),
    new WhiteCard('Les exercices pour stimuler l\'esprit d\'équipe en entreprise', false, 'all'),
    new WhiteCard('Plus Belle La Vie', false, 'all'),
    new WhiteCard('Se torcher', false, 'all'),
    new WhiteCard('L\'impuissance', false, 'all'),
    new WhiteCard('Un tir de son propre camp', false, 'all'),
    new WhiteCard('Les solos de saxophone', false, 'all'),
    new WhiteCard('Un énième film de vampires', false, 'all'),
    new WhiteCard('La kétamine', false, 'all'),
    new WhiteCard('Les oestrogènes', false, 'all'),
    new WhiteCard('Le Sud', false, 'all'),
    new WhiteCard('Vomir pour pouvoir manger', false, 'all'),
    new WhiteCard('Un bulot', false, 'all'),
    new WhiteCard('Des catapultes', false, 'all'),
    new WhiteCard('Un burrito très pimenté', false, 'all'),
    new WhiteCard('Les filles à qui l\'alcool ne réussit pas', false, 'all'),
    new WhiteCard('Des gobelins', false, 'all'),
    new WhiteCard('La Scientologie', false, 'all'),
    new WhiteCard('Nicolas Cage', false, 'all'),
    new WhiteCard('Une torsion musculaire', false, 'all'),
    new WhiteCard('La chair humaine', false, 'all'),
    new WhiteCard('La revente de cadeau sur eBay', false, 'all'),
    new WhiteCard('Une vidéo amateur de Claire Chazal qui sanglote au dessus d\'un plat surgelé', false, 'all'),
    new WhiteCard('Les chapeaux à hélices', false, 'all'),
    new WhiteCard('Où sont les toilettes', false, 'all'),
    new WhiteCard('Les Hot Pockets', false, 'all'),
    new WhiteCard('Des pilots kamikazes', false, 'all'),
    new WhiteCard('La lèpre', false, 'all'),
    new WhiteCard('Les concours de beauté pour enfants', false, 'all'),
    new WhiteCard('Les pantalons fendus en cuir des motards et des cow-boys', false, 'all'),
    new WhiteCard('Des oeufs de ptérodactyles', false, 'all'),
    new WhiteCard('Des couvertures avec la variole', false, 'all'),
    new WhiteCard('Le sexe oral non réciproque', false, 'all'),
    new WhiteCard('Des sucettes gérantes', false, 'all'),
    new WhiteCard('Gandhi', false, 'all'),
    new WhiteCard('Les soutifs lance-flammes', false, 'all'),
    new WhiteCard('Le Viagra', false, 'all'),
    new WhiteCard('Dr Martin Luther King Jr.', false, 'all'),
    new WhiteCard('Sean Penn', false, 'all'),
    new WhiteCard('Keanu Reeves', false, 'all'),
    new WhiteCard('L\'esclavage', false, 'all'),
    new WhiteCard('Genghis Khan', false, 'all'),
    new WhiteCard('Corky', false, 'all'),
    new WhiteCard('Un gardien de but', false, 'all'),
    new WhiteCard('Des oies', false, 'all'),
    new WhiteCard('Des refaits asymétriques', false, 'all'),
    new WhiteCard('Les hommes', false, 'all'),
    new WhiteCard('La bestialité', false, 'all'),
    new WhiteCard('Ce putain de jeu', false, 'all'),
    new WhiteCard('Le Médiator', false, 'all'),
    new WhiteCard('Des Chuppa Chups', false, 'all'),
    new WhiteCard('Will Smith', false, 'all'),
    new WhiteCard('La peluche "Elmo chatouille-moi"', false, 'all'),
    new WhiteCard('Les couteaux à cran d\'arrêt', false, 'all'),
    new WhiteCard('Des enfants avec un cancer du colon', false, 'all'),
    new WhiteCard('Des pancakes', false, 'all'),
    new WhiteCard('Céline Dion', false, 'all'),
    new WhiteCard('Une canette de Red Bull', false, 'all'),
    new WhiteCard('Le sang du Christ', false, 'all'),
    new WhiteCard('Ta mère qui me demande en ami sur Facebook', false, 'all'),
    new WhiteCard('Les gens en chaleur', false, 'all'),
    new WhiteCard('Les profs remplaçants', false, 'all'),
    new WhiteCard('Une parade nuptiale', false, 'all'),
    new WhiteCard('Avoir un calcul rénal', false, 'all'),
    new WhiteCard('La bagarre', false, 'all'),
    new WhiteCard('Jamie de "C\'est pas sorcier"', false, 'all'),
    new WhiteCard('Les piercings sur les parties génitales', false, 'all'),
    new WhiteCard('Les témoins de Jéhovah', false, 'all'),
    new WhiteCard('Les roux', false, 'all'),
    new WhiteCard('Sarah Palin', false, 'all'),
    new WhiteCard('L\'agriculture', false, 'all'),
    new WhiteCard('Le tri sélectif', false, 'all'),
    new WhiteCard('Les pornos SM allemands', false, 'all'),
    new WhiteCard('Un terroriste qui fait des vannes', false, 'all'),
    new WhiteCard('Une fusillade dans un lycée', false, 'all'),
    new WhiteCard('L\'avortement au cintre', false, 'all'),
    new WhiteCard('Le caca qui brule', false, 'all'),
    new WhiteCard('Mon statut relationnel', false, 'all'),
    new WhiteCard('Doigter', false, 'all'),
    new WhiteCard('Le SIDA', false, 'all'),
    new WhiteCard('Valérie Damidot', false, 'all'),
    new WhiteCard('Les rabat-joies', false, 'all'),
    new WhiteCard('Une lobotomie au pic à glace', false, 'all'),
    new WhiteCard('Un type louche en imperméable qui traîne devant les écoles primaires', false, 'all'),
    new WhiteCard('Les chinoises', false, 'all'),
    new WhiteCard('Un caniche nain', false, 'all'),
    new WhiteCard('Les trous dans les cloisons des WC sur les aires d\'autoroutes', false, 'all'),
    new WhiteCard('L\'ouragan Kratina', false, 'all'),
    new WhiteCard('Les Oreos', false, 'all'),
    new WhiteCard('Les nazis', false, 'all'),
    new WhiteCard('Les femmes dans les pubs de yaourts', false, 'all'),
    new WhiteCard('Les règles abondantes', false, 'all'),
    new WhiteCard('Les Frolics', false, 'all'),
    new WhiteCard('Les mines anti-personnels', false, 'all'),
    new WhiteCard('Une maison de retraite', false, 'all'),
    new WhiteCard('Le placenta', false, 'all'),
    new WhiteCard('Bono', false, 'all'),
    new WhiteCard('Justin Bieber', false, 'all'),
    new WhiteCard('La nécrophilie', false, 'all'),
    new WhiteCard('Un prépuce', false, 'all'),
    new WhiteCard('Indochine', false, 'all'),
    new WhiteCard('Le Big Bang', false, 'all'),
    new WhiteCard('Bob l\'éponge', false, 'all'),
    new WhiteCard('Ma collection de sex-toys high-tech', false, 'all'),
    new WhiteCard('La guérison par la foi', false, 'all'),
    new WhiteCard('Mon âme', false, 'all'),
    new WhiteCard('Aller à la messe de minuit', false, 'all'),
    new WhiteCard('Les connards sur leur iPhone', false, 'all'),
    new WhiteCard('La répression', false, 'all'),
    new WhiteCard('Improviser un dispositif à base d\'explosifs', false, 'all'),
    new WhiteCard('Draguer des personnes âgées', false, 'all'),
    new WhiteCard('Les éjaculations nocturnes', false, 'all'),
    new WhiteCard('Heath Ledger', false, 'all'),
    new WhiteCard('Les personnes âgées japonaises', false, 'all'),
    new WhiteCard('La Valse des Fleurs', false, 'all'),
    new WhiteCard('Une fellation au volant', false, 'all'),
    new WhiteCard('Les fantasmes sur les bûcherons', false, 'all'),
    new WhiteCard('Un téton qui sort du soutien-gorge', false, 'all'),
    new WhiteCard('Des bébés morts', false, 'all'),
    new WhiteCard('Être en feu', false, 'all'),
    new WhiteCard('La masturbation', false, 'all'),
    new WhiteCard('Le triangle des Bermudes', false, 'all'),
    new WhiteCard('Un océant de troubles', false, 'all'),
    new WhiteCard('La sélection naturelle', false, 'all'),
    new WhiteCard('Des parents morts', false, 'all'),
    new WhiteCard('Les italiens', false, 'all'),
    new WhiteCard('Tom Cruise', false, 'all'),
    new WhiteCard('La chevalerie', false, 'all'),
    new WhiteCard('Les jeux vidéo en réseau', false, 'all'),
    new WhiteCard('Le clitoris', false, 'all'),
    new WhiteCard('Le henta tentacules', false, 'all'),
    new WhiteCard('Mahomet', false, 'all'),
    new WhiteCard('Un gros ventre fendu qui ressemble à un cul', false, 'all'),
    new WhiteCard('La maltraitance sur mineur', false, 'all'),
    new WhiteCard('Toucher des organes génitaux par inadvertance', false, 'all'),
    new WhiteCard('Super Mario qui vient une fuite dans un film pornos', false, 'all'),
    new WhiteCard('Le Télétubbie qui fait le plus gay des quatre', false, 'all'),
    new WhiteCard('Les amis qui bouffent tous vos biscuits', false, 'all'),
    new WhiteCard('Paris Hilton', false, 'all'),
    new WhiteCard('Un mime qui fait une attaque', false, 'all'),
    new WhiteCard('Twitter', false, 'all'),
    new WhiteCard('Des préléminaires laborieux', false, 'all'),
    new WhiteCard('Un moment à soi', false, 'all'),
    new WhiteCard('Des gants en latex', false, 'all'),
    new WhiteCard('Porter ses sous-vêtements à l\'envers pour éviter de faire une machine', false, 'all'),
    new WhiteCard('Des crevettes à volonté pour 4,99 €', false, 'all'),
    new WhiteCard('Des échantillons gratuits', false, 'all'),
    new WhiteCard('Du kloug', false, 'all'),
    new WhiteCard('Un poil pubien abandonné', false, 'all'),
    new WhiteCard('Attendre jusqu\'au mariage', false, 'all'),
    new WhiteCard('Cette réponse est post-moderne', false, 'all'),
    new WhiteCard('Un Tamagotchi négligé', false, 'all'),
    new WhiteCard('Les décolletés élégants', false, 'all'),
    new WhiteCard('Des travestis potables', false, 'all'),
    new WhiteCard('Arnold Schwarzenegger', false, 'all'),
    new WhiteCard('Piller des tombes', false, 'all'),
    new WhiteCard('Un pistolet à eau remple de pipi de chat', false, 'all'),
    new WhiteCard('D\'Artagnan', false, 'all'),
    new WhiteCard('Ronald McDonald', false, 'all'),
    new WhiteCard('Se donner à 110%', false, 'all'),
    new WhiteCard('Nourrir Laurence Boccolini', false, 'all'),
    new WhiteCard('Un coup d\'oeil', false, 'all'),
    new WhiteCard('De multiples coups de couteaux', false, 'all'),
    new WhiteCard('Casimir', false, 'all'),
    new WhiteCard('Le meurtre le plus immonde', false, 'all'),
    new WhiteCard('Le périnée', false, 'all'),
    new WhiteCard('Ouvrir la Mer Rouge', false, 'all'),
    new WhiteCard('Trop de gel dans les cheveux', false, 'all'),
    new WhiteCard('Les vidéos porno hardcore', false, 'all'),
    new WhiteCard('Les sous-vêtements comestibles', false, 'all'),
    new WhiteCard('Les blancs', false, 'all'),
    new WhiteCard('Tiger Woods', false, 'all'),
    new WhiteCard('Descendre en piqué', false, 'all'),
    new WhiteCard('Coucher avec elle', false, 'all'),
    new WhiteCard('Coucher avec lui', false, 'all'),
    new WhiteCard('Les chants tyroliens dans les moments inappropriés', false, 'all'),
    new WhiteCard('K2000', false, 'all'),
    new WhiteCard('Les fantômes', false, 'all'),
    new WhiteCard('Un plan cul', false, 'all'),
    new WhiteCard('L\'intrigue d\'un film de Michael Bay', false, 'all'),
    new WhiteCard('La folie des hommes', false, 'all'),
    new WhiteCard('Un chapeau vraiment très cool', false, 'all'),
    new WhiteCard('La musique pop turque', false, 'all'),
    new WhiteCard('Robert Downey Jr.', false, 'all'),
    new WhiteCard('Nicolas Hulot', false, 'all'),
    new WhiteCard('Cacher une érection', false, 'all'),
    new WhiteCard('L\'herpès buccal', false, 'all'),
    new WhiteCard('Le comportement passif agressif', false, 'all'),
    new WhiteCard('Deux nains qui chient dans un seau', false, 'all'),
    new WhiteCard('Les pré-adolescentes', false, 'all'),
    new WhiteCard('Hippo Gloutons', false, 'all'),
    new WhiteCard('Kaune West', false, 'all'),
    new WhiteCard('Vomir sans vomi', false, 'all'),
    new WhiteCard('Eric Zemmour', false, 'all'),
    new WhiteCard('Les sans-abris', false, 'all'),', false, 'all'),
    new WhiteCard('Coco, le singe des Coco Pops', false, 'all'),
    new WhiteCard('Les échanges de politesse', false, 'all'),
    new WhiteCard('Des boules', false, 'all'),
    new WhiteCard('Le nettoyage ethnique', false, 'all'),
    new WhiteCard('Le truc du Télé Achat qui électrocute les abdominaux', false, 'all'),
    new WhiteCard('la gastro', false, 'all'),
    new WhiteCard('Des centaures', false, 'all'),
    new WhiteCard('Un uppercut', false, 'all'),
    new WhiteCard('Les nains', false, 'all'),
    new WhiteCard('Quand tu pètes et que ça fait un léger bruit', false, 'all'),
    new WhiteCard('Enlever ton t-shirt', false, 'all'),
    new WhiteCard('Monsieur Patate', false, 'all'),
    new WhiteCard('Un foetus', false, 'all'),
    new WhiteCard('Des blagues sur l\'Holocauste au moment inopportun', false, 'all'),
    new WhiteCard('Un spectacle de marionnettes', false, 'all'),
    new WhiteCard('Les pets vaginaux', false, 'all'),
    new WhiteCard('Un sunday caramel', false, 'all'),
    new WhiteCard('Des abeilles', false, 'all'),
    new WhiteCard('Le droit de vote aux femmes', false, 'all'),
    new WhiteCard('Bon, James Bond', false, 'all'),
    new WhiteCard('De la pâtée pour chat', false, 'all'),
    new WhiteCard('Le pudding à la figue', false, 'all'),
    new WhiteCard('Le soleil qui brille et les arcs en ciel', false, 'all'),
    new WhiteCard('Le réchauffement planétaire', false, 'all'),
    new WhiteCard('Boire de la bière en faisant le poirier sur le tonneau', false, 'all'),
    new WhiteCard('La règle de trois', false, 'all'),
    new WhiteCard('Porter des moufles', false, 'all'),
    new WhiteCard('Être fabuleux', false, 'all'),
    new WhiteCard('Buzz l\'Eclair qui explique le sexe aux enfants', false, 'all'),
    new WhiteCard('Manger tous les cookies qu\'on devait vendre à la kermesse', false, 'all'),
    new WhiteCard('Les émotions', false, 'all'),
    new WhiteCard('Du thon en boîte avec des bouts de dauphins', false, 'all'),
    new WhiteCard('Tricher aux Jeux Para-lympiques', false, 'all'),
    new WhiteCard('Une attaque de vélociraptors', false, 'all'),
    new WhiteCard('Une course à la mort en fauteuil roulant', false, 'all'),
    new WhiteCard('L\'attitude', false, 'all'),
    new WhiteCard('Les surdoués en mathématiques', false, 'all'),
    new WhiteCard('Les boules anales', false, 'all'),
    new WhiteCard('Les joueurs de djembé amateurs', false, 'all'),
    new WhiteCard('Un moulin à vent rempli de cadavres', false, 'all'),
    new WhiteCard('Hulk Hogan', false, 'all'),
    new WhiteCard('Le Smecta', false, 'all'),
    new WhiteCard('Des pédophiles', false, 'all'),
    new WhiteCard('Scalper', false, 'all'),
    new WhiteCard('Porter des semelles compensées', false, 'all'),
    new WhiteCard('La Gestapo', false, 'all'),
    new WhiteCard('La torture par l\'eau', false, 'all'),
    new WhiteCard('Les chorégraphies disco', false, 'all'),
    new WhiteCard('Chuck Norris qui casse de la lesbienne antisémite', false, 'all'),
    new WhiteCard('La Heineken', false, 'all'),
    new WhiteCard('Un micropénis', false, 'all'),
    new WhiteCard('Les oiseaux qui ne savent pas voler', false, 'all'),
    new WhiteCard('Braquer une banque du sperme', false, 'all'),
    new WhiteCard('Les quotas pour les minorités', false, 'all'),
    new WhiteCard('Un complexe d\'Oedipe', false, 'all'),
    new WhiteCard('Les combats de coqs', false, 'all'),
    new WhiteCard('La carrière musicale de Tony Parker', false, 'all'),
    new WhiteCard('Ma vie sexuelle', false, 'all'),
    new WhiteCard('Juliens Lepers', false, 'all'),
    new WhiteCard('Se saouler au bain de bouche', false, 'all'),
    new WhiteCard('La maladie de la vache folle', false, 'all'),
    new WhiteCard('Hara-kiri', false, 'all'),
    new WhiteCard('Piéger votre maison par peur des voleurs', false, 'all'),
    new WhiteCard('Le patinage artistique en duo non mixte', false, 'all'),
    new WhiteCard('Dark Vador', false, 'all'),
    new WhiteCard('Voldemort', false, 'all'),
    new WhiteCard('Lécher les choses pour prouver qu\'elles sont à vous', false, 'all'),
    new WhiteCard('Nicolas Sarkozy', false, 'all'),
    new WhiteCard('La Gay Pride', false, 'all'),
    new WhiteCard('La combustion spontanée', false, 'all'),
    new WhiteCard('Barack Obama', false, 'all'),
    new WhiteCard('Apprendre à un robot à aimer', false, 'all'),
    new WhiteCard('Sean Connery', false, 'all'),
    new WhiteCard('La paix mondiale', false, 'all'),
    new WhiteCard('La dépression nerveuse', false, 'all'),
    new WhiteCard('Les amputés', false, 'all'),
    new WhiteCard('Une mama black en colère', false, 'all'),
    new WhiteCard('Des talibans', false, 'all'),
    new WhiteCard('Le coeur d\'un enfant', false, 'all'),
    new WhiteCard('Être riche', false, 'all'),
    new WhiteCard('Des bananes en pyjamas', false, 'all'),
    new WhiteCard('Se gratter le cul ni vu ni connu', false, 'all'),
    new WhiteCard('Les golden showers', false, 'all'),
    new WhiteCard('Des victimes civiles', false, 'all'),
    new WhiteCard('Une érection qui dure plus de quatre heures', false, 'all'),
    new WhiteCard('Ces moments où vous avez du sable dans le vagin', false, 'all'),
    new WhiteCard('Se pavaner', false, 'all'),
    new WhiteCard('L\'obésité', false, 'all'),
    new WhiteCard('Les gays', false, 'all'),
    new WhiteCard('Les petits chanteurs à la croix de bois', false, 'all'),
    new WhiteCard('Faire un petit pipi', false, 'all'),
    new WhiteCard('Mourir', false, 'all'),
    new WhiteCard('Essayer de pécho de la meuf à la sortie des cliniques d\'avortement', false, 'all'),
    new WhiteCard('Les asiatiques que ne sont pas bons en maths', false, 'all'),
    new WhiteCard('Les garçons qui n\'appellent pas', false, 'all'),
    new WhiteCard('L\'odeur des vieux', false, 'all'),
    new WhiteCard('Un singe qui fume le cigare', false, 'all'),
    new WhiteCard('Une détonation thermonucléaire', false, 'all'),
    new WhiteCard('Kim Jong II', false, 'all'),
    new WhiteCard('Faire un câlin', false, 'all'),
    new WhiteCard('La vieille qui joue dans Arabesque', false, 'all'),
    new WhiteCard('La diarrhée des lendemains de fêtes arrosées', false, 'all'),
    new WhiteCard('L\'alcoolisme', false, 'all'),
    new WhiteCard('Le racisme', false, 'all'),
    new WhiteCard('Le catéchisme', false, 'all'),
    new WhiteCard('Les préservatifs parfumés', false, 'all'),
    new WhiteCard('Se réveiller à moitié nu sur le parking du McDo\'', false, 'all'),
    new WhiteCard('Le vagin de Whoopi Goldberg', false, 'all'),
    new WhiteCard('Monsieur Propre', false, 'all'),
    new WhiteCard('Les pauvres', false, 'all'),
    new WhiteCard('L\'envie de pénis', false, 'all'),
    new WhiteCard('Les mexicains qui travaillent dur', false, 'all'),
    new WhiteCard('Douce, douce vengeance...', false, 'all'),
    new WhiteCard('Le COVID-19', false, 'all'),
    new WhiteCard('L\'hécatombe dans les EPHAD', false, 'all'),
];
